language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.1.0

before_install:
  - echo yes | android update sdk --filter platform-tools --no-ui --force
  - echo yes | android update sdk --all --filter build-tools-19.1.0 --no-ui --force

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - chmod +x gradlew
  - ./gradlew assemble